# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: â“ Discussion
    url: https://github.com/PeriHub/PeriHub/discussions/new/choose
    about: Please ask and answer questions here. ğŸ¥
